In [1]:
import pandas as pd

firstname_df = pd.read_csv("/project/lt200324-optmul/pluem/csv_data/firstname_corpus_18sep.csv")
lastname_df = pd.read_csv("/project/lt200324-optmul/pluem/csv_data/lastname_corpus_21aug.csv")

In [2]:
from tqdm import tqdm

def generate_random_names(firstname_df, lastname_df, num_combinations=1):
    results = []
    for _ in tqdm(range(num_combinations)):
        # Randomly select a first name and a last name
        first_name = firstname_df.sample(n=1).iloc[0]
        last_name = lastname_df.sample(n=1).iloc[0]

        # Combine the names
        full_name = f"{first_name['firstname']} {last_name['lastname']}"

        results.append({'name': full_name})

    return pd.DataFrame(results)

In [3]:
# Generate random combinations
result = generate_random_names(firstname_df, lastname_df, num_combinations=5600000)
result

100%|██████████| 5600000/5600000 [40:25<00:00, 2309.20it/s]

                         name
0           อิสริยา วุฑฒิโชติ
1                มนัสพร ตปาคม
2                สุชาติ เทพธร
3          จิตรีภรณ์ กีสะบุตร
4           ซูฮัยดา ยุกตานนท์
...                       ...
5599995  อัซมีน วรภัทรจิรธาดา
5599996   ปภาวรินท์ สามนกฤษณะ
5599997  พิเชษฐไชย มิลินทะทัต
5599998     กุลนิษฐ์ สุนทรนาค
5599999     ภาพตะวัน ชาตปัทมะ

[5600000 rows x 1 columns]

In [4]:
# Remove duplicate rows based on 'name' columns
new_result = result.drop_duplicates(subset=['name'])
new_result = new_result.reset_index(drop=True)
new_result

                         name
0           อิสริยา วุฑฒิโชติ
1                มนัสพร ตปาคม
2                สุชาติ เทพธร
3          จิตรีภรณ์ กีสะบุตร
4           ซูฮัยดา ยุกตานนท์
...                       ...
5225858      สุนทร อินทวาศวิน
5225859   ปภาวรินท์ สามนกฤษณะ
5225860  พิเชษฐไชย มิลินทะทัต
5225861     กุลนิษฐ์ สุนทรนาค
5225862     ภาพตะวัน ชาตปัทมะ

[5225863 rows x 1 columns]

In [6]:
subset = new_result.head(5000000)
name_list = subset['name'].tolist()
len(name_list)

5000000

In [7]:
name_list[:10]

['อิสริยา วุฑฒิโชติ',
 'มนัสพร ตปาคม',
 'สุชาติ เทพธร',
 'จิตรีภรณ์ กีสะบุตร',
 'ซูฮัยดา ยุกตานนท์',
 'ณฑพล บุณยตุลย์',
 'กิตติธรา จูฬติตตะ',
 'เมธัส อัญชลิสังกาศ',
 'ปริญญาพร สุขะวรรณ',
 'ภัทรกร สายะเวส']

In [8]:
with open(f'/project/lt200324-optmul/pluem/version_2/dataset/name/name.txt', 'w', encoding='utf-8') as file:
    file.write('\n'.join(line.strip() for line in name_list))